---
title: "R Notebook"
output: html_notebook
---

Introduccion a Tydiverse

```{r}
library(gapminder)
library(dplyr)

gapminder
```

Filtering

```{r}
gapminder %>%
  filter(year == 1957)
```

Arrange

```{r}
gapminder %>% 
  arrange(desc(lifeExp))
```

Filtering and arranging

```{r}
gapminder %>%
  filter(year == 1957) %>%
  arrange(desc(pop))
```

Verbo mutate

```{r}
gapminder %>%
  mutate(lifeExp = 12 * lifeExp )

gapminder %>%
  mutate(lifeExpMonths = 12 * lifeExp )

```

Combining filter, mutate and arrange


```{r}
gapminder %>%
  filter(year == 2007) %>%
  mutate(lifeExpMonths = 12 * lifeExp ) %>%
  arrange(desc(lifeExpMonths))
```
```{r}
library(ggplot2)

gapminder_1952 <- gapminder %>%
  filter(year == 1952)

gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + 
  geom_point()

```

Escala logaritmica

```{r}
ggplot(gapminder_1952, aes(x=pop, y=gdpPercap)) + 
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```



```{r}
ggplot(gapminder_1952, aes(x=pop, y=lifeExp, color=continent, size = gdpPercap)) + 
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```
```{r}
gapminder_1952

ggplot(gapminder_1952, aes(x=pop, y=lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ continent)
```

```{r}
ggplot(gapminder, aes(x=gdpPercap, y=lifeExp)) +
  geom_point() +
  scale_x_log10() +
  facet_wrap(~ year)
```


