---
title: "R Notebook"
output: html_notebook
---

```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

```

Greater and less than

```{r}
-6 * 5 + 1 >= -10 + 1
"raining" <= "table"
TRUE > FALSE
```


Compare vectors

```{r}
linkedin <- c(15,23,13,5,1,13,14)
facebook <- c(14,36,21,2,3,12,3) 

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin, facebook), nrow=2, byrow=TRUE)
views

views == 13
views <= 14

views[views<15]

```

Logical operators

```{r}

linkedin <= 10 | facebook == 13
views > 11 & views <= 14
```
If statement

```{r}
medium <- "Facebook"
num_views <- 14

if(medium == "Linkedin") {
  print("Showing linkedin information")
} else {
  print("Unknown medium")
}

if(num_views > 15) {
  print("you're popular")
} else {
  print("Try to be more visible!")
}

```

Customize further: else if

```{r}

if(medium == "Linkedin") {
  print("Showing linkedin information")
} else if (medium == "Facebook") {
  print("Showing Facebook information")
} else {
  print("Unknown medium")
}

```
Else if 2.0

```{r}
number <-19
result <- ""
if( number < 10 ) {
  if( number < 5 ){
    result <- "extra small"
  }else {
    result <- "small"
  }
} else if (number < 100) {
  result <- "medium"
} else {
  result <- "medium"
}

print(result)

```


