---
title: "R Notebook"
output: html_notebook
---

Aritmetica en R

```{r}
21 + 26
23 - 12
5*2
(5-2)/12
2^2
28%%6
```

Asignacion de variables

```{r}
x <- 10
y <- 15
total = x + y
total
```

Tipos de datos

```{r}
my_character <- "universe"
my_logical <- FALSE 

my_character
my_logical
```

```{r}
class(my_character)
class(my_logical)
```


Vectores

```{r}
numeric_vector <- c(1, 10, 49)
numeric_vector 

vector2 <- c(1,2, "3")
vector2

vector3 <- c(TRUE, FALSE, TRUE)
vector3
```



Nombrar vector

```{r}
pocker_vector <- c(140, -50, 12, 43, 24)
roulette_vector <- c(140, -50, 12, 43, 24)


names(pocker_vector) = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday")
pocker_vector

```

Comparando y seleccionando

```{r}
age <- 17
result = age >= 18
result

a_vector = c(1,2,3,4,5)
b_vector = c(6,2,1,3,4)

total_vector = a_vector + b_vector
total_vector

total_daily = pocker_vector + roulette_vector
total_daily

total_pocker = sum(pocker_vector)
total_pocker

pocker_vector[c(1,3,4)]

selection_vector <-pocker_vector > 0
pocker_vector[selection_vector]

```
Matrices 

```{r}
matrix(1:9, byrow=TRUE, nrow=3)
```


```{r}
new_hope <- c(460.998, 314.4)
empire_strike <- c(2980.475, 247.900)
return_jedi <- c(309.306, 165.8)

box_office <- c(new_hope, empire_strike, return_jedi)

star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
star_wars_matrix

region <- c("US", "non-US")
titles <- c("A new hope", "The empire strikes back", "Return of the Jedi")

colnames(star_wars_matrix) <- region
rownames(star_wars_matrix) <- titles 

star_wars_matrix

```
rowSums

```{r}
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector
''
all_wars_variable <- cbind(star_wars_matrix, worldwide_vector)
all_wars_variable

worldwide_cols <- colSums(all_wars_variable)
worldwide_cols

all_wars_variable <- rbind(all_wars_variable, worldwide_cols)
all_wars_variable
```
Selection of matrix elements

```{r}

non_us_all = all_wars_variable[1:3,2]
non_us_all

mean(non_us_all)
```

Aritmetica de matrices

```{r}

us_all <- all_wars_variable[1:3, 1]
us_all <- us_all * 0.12
us_all

```

Factors

```{r}

sex_vector <- c("Male", "Female", "Female", "Male", "Male")

factor_sex_vector <- factor(sex_vector)
factor_sex_vector

temperature_vector = c("High", "Low", "High", "Low", "Medium")
factor_temperature_vector = factor(temperature_vector, order = TRUE, levels= c("Low", "Medium", "High") )
factor_temperature_vector

```
Factor levels

```{r}

survey_vector = c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
factor_survey_vector

levels(factor_survey_vector) <- c("Female", "Male")
factor_survey_vector
```
Summarize vector 

```{r}

summary(survey_vector)
summary(factor_survey_vector)

male <- factor_survey_vector[1]
male

female <- factor_survey_vector[2]
female


speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered=TRUE, levels=c("slow", "medium", "fast"))
factor_speed_vector

da2 <- factor_speed_vector[2]
da1 <- factor_speed_vector[1]

da2
da1

da2 < da3


```


Dataframes 

```{r}

mtcars

head(mtcars)
tail(mtcars)
```

