---
title: "R Notebook"
output: html_notebook
---

```{r}
sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')

library(tidyverse)

```

```{r}
counties <- read_csv("counties.csv")
counties 

counties %>%
  select(state, county, population, professional : production)

counties %>%
  select(state, county, population, contains("per"))

```

```{r}

counties %>%
  count(state) %>%
  rename(num_counties = n)

counties %>%
  select(state, county, poverty_rate = poverty)

```

Transmute

```{r}

counties %>%
  transmute(state, county, population, density = population/land_area) %>%
  filter(population > 1000000) %>%
  arrange(density)
```



```{r}

counties %>%
  rename(unemployment_rate = unemployment)

counties %>%
  select(state, county, contains("poverty"))

```

```{r}
counties %>%
  mutate(fraction_woman= women/population)

counties %>%
  transmute(state, county,  employment_rate = employed / population)

```




Joining data with dplyr

```{r}
sets
themes
```



```{r}
sets %>%
  inner_join(themes, by= c("theme_id" = "id") )
```

```{r}
view(parts)
view(part_categories)

view_parts <- parts %>% 
  inner_join(part_categories, by = c("part_cat_id" = "id"))

view(view_parts)

view_parts <- parts %>% 
  inner_join(part_categories, by = c("part_cat_id" = "id"), suffix = c("_parts", "_parts_categories") )

view(view_parts)

```

























