---
title: "R Notebook"
output: html_notebook
---

Functions

```{r}
pow_two <- function(x, print_info=TRUE){
  y = x ^2
  if(print_info){
    print(paste(x, "to the power of two equals", y))
  }
  y
}

result = pow_two(3)
result

```
Function scoping

```{r}
pow_two <- function(x){
  y <- x^2
  y
}
pow_two(4)
y
```

R passes arguments by value

```{r}
triple <- function(x){
  x <- 3*x
  x
}

a <- 5
triple(a)
a
```

Other type of parameters
```{r}
linkedin <- c(17,23,13,5,1,13,14)

interpret <- function(num_views){
  if(num_views > 15){
    print("You re popular")
    return(num_views)
  }else{
    print("Try to be more visible!")
    return(0)
  }
}

interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  
  for(v in views){
    count = count+ interpret(v)
  }
  
  if(return_sum){
    return (count)
  }else {
    return (NULL)
  }
}

interpret_all(linkedin)

```

Load an R Package

```{r}
library(ggplot2)

qplot(mtcars$wt, mtcars$hp)
```

Use apply with R

```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

l = lapply(temp, min)
l
class(l)

for(t in temp){
  print(min(t))
}
```

lapply and anonymous functions

```{r}

pioneers <- c("Gauss:1777", "Bayes:1702", "PASCAL:1623", "Pearson:1857")

split <- strsplit(pioneers, split=":")

split_low <- lapply(split, tolower)

split
split_low

names <- lapply(split_low, function(x){ x[1] })
names

years <- lapply(split_low, function(x){ x[2] })
years
```
Use lapply with additional arguments

```{r}

select_el <- function(x, index){
  x[index]
}

names <- lapply(split_low, select_el, index = 1)
names

years <- lapply(split_low, select_el, index=2)
years

```
sapply

```{r}
extremes <- function(x){
  c(min=min(x), max= max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)

temp2 <- list(1,2,3,4,5)
temp2

func_temp2 <- function(x){
  x
}

lapply(temp2, func_temp2)
sapply(temp2, func_temp2)

```

vapply

```{r}
basics <- function(x){
  c(min=min(x), mean=mean(x), max=max(x))
}

lapply(temp, basics)

sapply(temp, basics)

vapply(temp, basics, numeric(3))

temp3 <- c("Guatemala", "Honduras")



```
utilities

```{r}
errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)
print(sum(abs(round(errors))))

?round

linkedin <- list(16, 9, 13, 5, 2, 17, 14)
facebook <- list(17, 7, 5, 16, 8, 13, 14)

li_vec <- unlist(linkedin)
fb_vec <- unlist(facebook)

social_vec <- append(li_vec, fb_vec)
social_vec

sort(social_vec, decreasing = TRUE)

```


grep y grepl

```{r}
emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org",
            "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")
grepl(pattern = "edu", x=emails)

hits <- grepl(pattern = "edu", x=emails)

emails[hits]

```




































